name: cats-effect-time
baseurl: /cats-effect-time
description: Java Time from Cats-Effect
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.0+6-c3a3de95-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
