name: cats-effect-time
baseurl: /cats-effect-time
description: Java Time from Cats-Effect
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.4+2-19bf0c63-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
