name: cats-effect-time
baseurl: /cats-effect-time
description: Java Time from Cats-Effect
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.0+10-5828134b-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
