name: cats-effect-time
baseurl: /cats-effect-time
description: Java Time from Cats-Effect
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.4+19-0b6c6d66-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
